#!/bin/bash

echo "reviving supervisor..."
cd /etc/service
ln -s /opt/atlantis-supervisor atlantis-supervisor
i=0
while [ -z "$(pidof supervisor)" ] && [ $i -lt 10 ]; do
  echo "waiting for supervisor to revive..."
  sleep 2
  if [ -p /opt/atlantis-supervisor/supervise/ok ]; then
    sv up atlantis-supervisor
  fi
  (( i++ ))
done
if [ $i -eq 10 ]; then
  echo "could not revive supervisor."
  exit 1
fi
echo "supervisor revived."
